name       : horst
version    : 4.2.0
release    : 1
homepage   : http://br1.einfach.org/tech/horst/
source     :
    - http://br1.einfach.org/horst_dl/horst-4.2.tar.gz : eab46330998a4c6d5abc9bfdad739b62b57c65049ac6f160e58ee3edd3260057
license    : GPL-2.0
summary    : A small, lightweight IEEE802.11 wireless LAN analyzer with a text interface.
builddeps  :
description: |
    A small, lightweight IEEE802.11 wireless LAN analyzer with a text interface.
build      : |
    %make
install    : |
    mkdir -p $installdir/usr/bin
    mkdir -p $installdir/usr/share/man/man1
    mkdir -p $installdir/usr/share/doc/horst
    cp horst $installdir/usr/bin/
    cp horst.1 $installdir/usr/share/man/man1/
    cp README LICENSE $installdir/usr/share/doc/horst/
