name       : horst
version    : 5.0
release    : 2
homepage   : http://br1.einfach.org/tech/horst/
source     :
    - https://github.com/br101/horst/archive/version-5.0.tar.gz : ea19cc0565b0bc8e001d11d4480030ef8ade67f85b2ddd28f6eb9233cb1e5c5b
license    : GPL-2.0
component  : network.util
summary    : A small, lightweight IEEE802.11 wireless LAN analyzer with a text interface.
description: |
    A small, lightweight IEEE802.11 wireless LAN analyzer with a text interface.
builddeps  :
    - pkgconfig(libnl-3.0)
build      : |
    %make
install    : |
    install -Dm00755 horst $installdir/usr/bin/horst
    install -Dm00644 horst.1 $installdir/usr/share/man/man1/horst.1
