name       : horst
version    : '5.1'
release    : 4
homepage   : https://github.com/br101/horst
source     :
    - https://github.com/br101/horst/archive/v5.1.tar.gz : 74b4cb1143d93c73c3b4bbbe0c36f89a790401bde9e894e94e2a27339ca384d9
license    : GPL-2.0-or-later
component  : network.util
summary    : A small, lightweight IEEE802.11 wireless LAN analyzer with a text interface
description: |
    A small, lightweight IEEE802.11 wireless LAN analyzer with a text interface.
builddeps  :
    - pkgconfig(libnl-3.0)
build      : |
    %make
install    : |
    install -Dm00755 horst $installdir/usr/bin/horst
    install -Dm00644 horst.conf $installdir/etc/horst.conf
    install -Dm00644 horst.conf.5 $installdir/usr/share/man/man5/horst.conf.5
    install -Dm00644 horst.8 $installdir/usr/share/man/man8/horst.8
